services:
    oro_featuretoggle.event_listener.request:
        class: 'Oro\Bundle\FeatureToggleBundle\EventListener\RequestListener'
        arguments:
            - '@oro_featuretoggle.checker.feature_checker'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }